### PR TITLE
add `--stdio` option

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Some editors (e.g. neovim) do not support "lsp over tcp"

### CODE REVIEW

**Comment by n8henrie** [comment]
@MaxVerevkin any chance you could share your neovim setup to take advantage of this (or perhaps it's available elsewhere)?

I see [a configuration](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#openscad_ls) for <https://github.com/dzhu/openscad-language-server> but not for this library.

**Comment by MaxVerevkin** [comment]
@n8henrie I basically use what `lspconfig` plugin provides, but with a small local change (this should be upstreamed?):

```diff
diff --git a/lua/lspconfig/server_configurations/openscad_ls.lua b/lua/lspconfig/server_configurations/openscad_ls.lua
index e5ca9ca..177e5fa 100644
--- a/lua/lspconfig/server_configurations/openscad_ls.lua
+++ b/lua/lspconfig/server_configurations/openscad_ls.lua
@@ -2,7 +2,8 @@ local util = require 'lspconfig.util'
 
 return {
   default_config = {
-    cmd = { 'openscad-language-server' },
+    cmd = { 'openscad-lsp', '--stdio' },
     filetypes = { 'openscad' },
     root_dir = util.find_git_ancestor,
     single_file_support = true,
```

**Comment by n8henrie** [comment]
That's basically what I've been trying, just omitting the settings that have reasonable defaults:

```lua
local nvim_lsp = require("lspconfig")
nvim_lsp.openscad_ls.setup({
  on_attach = default_lsp_on_attach,
  cmd = {
    "/path/to/openscad-lsp",
    "--stdio",
  },
})
```

where:
- `default_lsp_on_attach` works fine for all my other language servers (and omitting it doesn't help)
- `$ /path/to/openscad-lsp --stdio` seems to work (I see appropriate output)
- I have filetype detection working fine `:set filetype?`

I don't see the language server process even starting up. Weird.

**Comment by n8henrie** [comment]
@MaxVerevkin after a couple hours of debugging the issue solved itself with no code changes. Got it working with a dummy `init.lua`, tried debugging all the plugins one by one, starting working at some point, re-enabled all plugins, continues working. *heavy sigh*

Thanks for your time and attention.

**Pull request merged**
